sudo: required
services:
  - docker

script:
  - docker build -t taldesigns/node .
  - docker images taldesigns/node

before_deploy:
  - docker login -u talgatt -p Moldir$96

deploy:
  provider: script
  script: docker push taldesigns/node
  on:
    branch: master
